config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "projects#index"
  resources :projects

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
    validates :title, presence: true
    validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# This is a basic HomeController with an index that does one thig: render 
# the view file associated with the controller action

class HomeController < ApplicationController
    def index
        render
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>CS3300 Portfolio Project</title>

  </head>
  
  <body>
    <div style="margin: 5% 0 0 10%;">
    <h1>Projects</h1>   
    <h1>CS 3300 Portfolio Project - Fall 2022</h1>

      <div style="padding-left: 2rem;">
        <h4 style="color: blue"> Grayson Mckenzie </h4>
        

        <!--- Explain what the block of code below this line is doing --->
        #checks if the user signed in or out and provides proper actions for both
        <% if user_signed_in? %>
          
          <div> Welcome <%= current_user.email %> </div>
          <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
        
        <% else %>
          <a href="/users/sign_in"> Sign in</a>
        <% end %>

      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<style>
.navbar{
  background-color: Navy!important;
  margin-bottom:0px;
  padding:1rem!important;
}
.notice {
  margin:0px;
  padding:0px;
}
.alert{
  margin:0px!important;
  padding:0!important;
}
body{
  margin: 0px;
  padding:0px;
  background-color: SteelBlue!important;
}

.div-centered {
  text-align: left; 
  padding-left: 11.35%;
  padding-right: 11.35%;
  align-items: top;
}
.button{
  background-color: Navy;
  font-size:25px;
  border-style:none;
  border-radius: 10px;
  color:LightGrey;
  -webkit-appearance: button;
  -moz-appearance: button;
  appearance: button;
  text-decoration: none;
  padding: 1rem;
}
.button:hover{
  color:white;
  background-color: SteelBlue;
}

#form{
  font-size: 20px;
  color: Azure;
  background-color: Navy;
  border-style: solid;
  border-color: SteelBlue;
  border-width: 5px;
  border-radius: 5px;
  padding: 10px;
}
#intro{
  background-color: Navy;
  color: Azure;
  width: 100%;
  margin-bottom: 2rem;
  padding-left: 11.35%;
  padding-top: 2rem;
  padding-bottom: 2rem;
}
#page-title{
  font-size: 60px;
}
#back-banner{
  background-color: Azure!important;
  margin-left: 10%;
  margin-right: 10%;
  height: 100vh;
}

</style>
  <head>
    <title>Cs3300project2022</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" ></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body>
  <nav class="navbar navbar-expand navbar-primary">
  <a class="navbar-brand text-light" href="projects#index">Grayson Mckenzie</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse" id="navbarContent">
        <ul class="navbar-nav">
            <li class="nav-item">
            <a class="nav-link text-light" href="projects#index"> Home </a>
            </li>
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-light" href="#" role="button" id="accountDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Account </a>

            <% if user_signed_in? %>
            <div class="dropdown-menu" aria-labelledby="accountDropdown">
            <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
            <div>
          <% else %>
            <div class="dropdown-menu" aria-labelledby="accountDropdown">
                <a class="dropdown-item" href="users/sign_in">Log In</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="users/sign_up">Sign Up</a>
                </div>
          <% end %>

                
            </li>
        </ul>
    </div>
</nav>
    <p class="notice"><%= notice %></p> 
    <p class="alert"><%= alert %></p> 
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<style>
label{
  font-size: 30px;
}
</style>
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div id= "title">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, :required => 'required' %>
  </div>

  <div id="description">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, :required => 'required' %>
  </div>

  <div id="submit">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Title:</strong>
    <%= project.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<!DOCTYPE html>
<html lang="en">
<style>

</style>
<body>
<!--- <p style="color: green"><%= notice %></p> --->
<div id="back-banner">
<div id="intro">
<h1 id="page-title">My Portfolio</h1>

<p>Hello, I am Grayson Mckenzie and this is my portfolio. All of my projects will be listed below.</p>
</div>
<div class="div-centered" id="content">
<h2>Projects</h2>
<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<a class="button" href="projects/new">Create New Project</a>
<!--- <%= link_to "New project", new_project_path %> --->
</div>
</div>
</body>
</html>

app/views/projects/new.html.erb
<!DOCTYPE html>
<html lang="en">
<body>
<div id="back-banner">

<div id="intro">  <h1 id="page-title">New Project</h1></div>

<div class="div-centered" id="content">

  <div id="form">
  <%= render "form", project: @project %>
  </div>
  <br>

  <a class="button" href="../">Back to projects</a>
  <!--- <%= link_to "Back to projects", root_path %> --->
</div>
</div>
</body>
</html>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project) %> |
  <%= link_to "Back to projects", projects_path %>

  <%= button_to "Destroy this project", @project, method: :delete %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>